import type { Metadata } from "next";
import "./globals.css";
import { Work_Sans, Instrument_Sans } from "next/font/google";
import Footer from "./components/footer";
import HeaderMain from "./components/HeaderMain";
import GraphQlProvider from "./providers/GraphQLProvider";


const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-primary"

});

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-secondary"

});



export const metadata: Metadata = {
  title: "Arttescapee by Sanjana",
  description: "Generated by create next app",
  icons: ["https://passionate-animal-cebee928de.media.strapiapp.com/Screenshot_2026_02_10_133152_fabb9ad9e0.png"]
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable} ${instrumentSans.variable} antialiased`}
      >
        <GraphQlProvider>
          <HeaderMain />
          {children}
          <Footer />
        </GraphQlProvider>

      </body>
    </html>
  );
}
